### ISSUE TITLE
USER: Log-in and Log-out

### ISSUE THREAD

**Issue by sarahgoodwin93** [sarahgoodwin93/wild-swim-scotland#9]
As a site user, I can log in with my created username and password to access the site and see my previous actions

AC1 - Site user can log in with their created username and password after they have registered to the site

AC2 - Site users can see the swims they have registered from a previous login

AC 3 - Site user can log out when they have finished their session and confirm they want to log out

**Tasks**
- [ ] Link accounts/login template so that users can sign into the site
- [ ] Link accounts/logout template so that users can sign out of the site
- [ ] Ensure data is saved from previous login so that users can see their previous swim actions
